name: CD
run-name: ${{inputs.destroy && 'Destroy' || 'Deploy to' }} ${{ inputs.env || 'Dev/Test/Prod' }}

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
      destroy:
        description: 'Destroy infrastructure'
        required: false
        type: boolean
        default: false
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  check_ci_success:
    if: ${{ github.event_name == 'workflow_run' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail if CI did not succeed
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "CI workflow did not succeed. Failing CD workflow."
            exit 1
          fi
  deploy:
    name: ${{inputs.env}} - Deploy
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.env != '' }}
    uses: ./.github/workflows/tf-deploy-template.yml
    with:
      env: ${{ inputs.env }}
      destroy: ${{ inputs.destroy }}

  dev-tf:
    name: Dev - TF Deploy
    needs: check_ci_success
    uses: ./.github/workflows/tf-deploy-template.yml
    with:
      env: dev

  test-tf:
    name: Test - TF Deploy
    needs: dev-tf
    uses: ./.github/workflows/tf-deploy-template.yml
    with:
      env: test

  prod-tf:
    name: Prod - TF Deploy
    needs: test-tf
    uses: ./.github/workflows/tf-deploy-template.yml
    with:
      env: prod
