name: CI/CD

# PR Validation: "Build/Validate"
# Push to main: "Deploy - Dev/Test/Prod"
# Manual Dispatch: "Deploy - {env}" or "Destroy - {env}"
run-name: ${{(github.event_name == 'pull_request' && 'Build/Validate') || (inputs.destroy && 'Destroy') || 'Deploy' }}${{ github.event_name != 'pull_request' && (inputs.env && format(' - {0}', inputs.env) || ' - Dev/Test/Prod') || '' }}

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: false
        type: choice
        options:
          - '' # If no env selected, run full CI/CD workflow/deploy to all envs
          - dev
          - test
          - prod
      destroy:
        description: 'Destroy infrastructure'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Replace this with actual unit test steps
      - name: Run Unit Tests
        run: echo "Running unit tests..."

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Replace this with actual build steps
      - name: Build Application
        run: echo "Building application..."

  tf-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.14.x'
      - name: Terraform init
        run: terraform init -backend=false
        working-directory: infra
      - name: Terraform validate
        run: terraform validate
        working-directory: infra
      - name: Terraform fmt check
        if: ${{ github.event_name == 'pull_request' }}
        run: terraform fmt -check -recursive
        working-directory: infra

  # Check if all validations have passed
  gate:
    name: Deployment Gate
    needs: [tf-validate, build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Gate
        run: echo "Deployment gate passed."

  # Full CI/CD Deployment is triggered if it is CI trigger (main branch) or a manual dispatch for all envs (no env selected)
  cd-gate:
    name: CD (all envs)
    needs: [gate]
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.env == '') }}
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Gate
        run: echo "Deployment gate passed."

  # Deploy/Destroy on workflow_dispatch to selected environment only
  deploy:
    name: Deploy ${{inputs.env}}
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.env != '' }}
    needs: [gate]
    uses: ./.github/workflows/deploy-template.yml
    with:
      env: ${{ inputs.env }}
      destroy: ${{ inputs.destroy }}

  # Normal CI/CD flow for all environments
  dev-deploy:
    name: Dev - Deploy
    needs: [cd-gate]
    uses: ./.github/workflows/deploy-template.yml
    with:
      env: dev

  test-deploy:
    name: Test - Deploy
    needs: [dev-deploy]
    uses: ./.github/workflows/deploy-template.yml
    with:
      env: test

  prod-deploy:
    name: Prod - Deploy
    needs: [test-deploy]
    uses: ./.github/workflows/deploy-template.yml
    with:
      env: prod
